# Generated by Django 5.0.2 on 2024-02-18 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TamagotchiCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user_owned_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TamagotchiMood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hunger", models.FloatField(default=100.0)),
                ("rest", models.FloatField(default=100.0)),
                ("rest_start_time", models.DateTimeField()),
                ("long_time_activity_id", models.IntegerField()),
                ("last_interaction_time", models.DateTimeField(auto_now_add=True)),
                (
                    "tamagotchi_related_to_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tamagotchi.tamagotchicharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_id", models.CharField(max_length=32, unique=True)),
                ("description", models.CharField(max_length=320)),
                (
                    "user_related_to_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
