# Generated by Django 5.0.2 on 2024-02-18 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="Custom_User_Profile",
        ),
        migrations.RenameModel(
            old_name="TamagotchiCharacter",
            new_name="Tamagotchi_Character",
        ),
        migrations.RenameModel(
            old_name="TamagotchiMood",
            new_name="Tamagotchi_Mood",
        ),
    ]
