# Generated by Django 5.0.2 on 2024-02-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0002_rename_userprofile_custom_user_profile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="custom_user_profile",
            old_name="user_related_to_id",
            new_name="user_related_to",
        ),
        migrations.RenameField(
            model_name="tamagotchi_character",
            old_name="user_owned_id",
            new_name="user_owned",
        ),
        migrations.RenameField(
            model_name="tamagotchi_mood",
            old_name="tamagotchi_related_to_id",
            new_name="tamagotchi_related_to",
        ),
    ]
