# Generated by Django 5.0.2 on 2024-03-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tamagotchi",
            "0003_rename_user_related_to_id_custom_user_profile_user_related_to_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tamagotchi_Look",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hat_id", models.IntegerField(choices=[(0, "Red"), (1, "Blue")])),
                (
                    "tshirt_id",
                    models.IntegerField(choices=[(0, "Green"), (1, "Yellow")]),
                ),
                (
                    "tamagotchi_related_to",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tamagotchi.tamagotchi_character",
                    ),
                ),
            ],
        ),
    ]
