# Generated by Django 5.0.2 on 2024-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0004_tamagotchi_look"),
    ]

    operations = [
        migrations.AddField(
            model_name="tamagotchi_mood",
            name="health",
            field=models.FloatField(default=100.0),
        ),
    ]
