# Generated by Django 5.0.2 on 2024-03-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0005_tamagotchi_mood_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hat_images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Tamagotchi_type_images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.RemoveField(
            model_name="tamagotchi_look",
            name="hat_id",
        ),
        migrations.RemoveField(
            model_name="tamagotchi_look",
            name="tshirt_id",
        ),
        migrations.AddField(
            model_name="tamagotchi_mood",
            name="mood",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="tamagotchi_look",
            name="hat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tamagotchi.hat_images",
            ),
        ),
        migrations.AddField(
            model_name="tamagotchi_look",
            name="tamagotchi_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tamagotchi.tamagotchi_type_images",
            ),
        ),
    ]
