# Generated by Django 5.0.2 on 2024-03-24 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0006_hat_images_tamagotchi_type_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tamagotchi_look",
            name="hat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tamagotchi.hat_images"
            ),
        ),
        migrations.AlterField(
            model_name="tamagotchi_look",
            name="tamagotchi_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tamagotchi.tamagotchi_type_images",
            ),
        ),
    ]
