# Generated by Django 3.2.25 on 2024-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamagotchi', '0007_alter_tamagotchi_look_hat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamagotchi_mood',
            name='number_of_click',
            field=models.IntegerField(default=50),
        ),
    ]
