# Generated by Django 5.0.6 on 2024-05-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0008_tamagotchi_mood_number_of_click"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tamagotchi_mood",
            name="mood",
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="health",
            field=models.FloatField(default=80.0),
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="hunger",
            field=models.FloatField(default=80.0),
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="number_of_click",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="rest",
            field=models.FloatField(default=80.0),
        ),
    ]
