# Generated by Django 5.0.6 on 2024-05-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0009_remove_tamagotchi_mood_mood_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="health",
            field=models.FloatField(default=85.0),
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="hunger",
            field=models.FloatField(default=85.0),
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="rest",
            field=models.FloatField(default=85.0),
        ),
    ]
