# Generated by Django 5.0.6 on 2024-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0010_alter_tamagotchi_mood_health_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tamagotchi_mood",
            name="long_time_activity_id",
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="last_interaction_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="tamagotchi_mood",
            name="rest_start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
