# Generated by Django 5.0.6 on 2024-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0011_remove_tamagotchi_mood_long_time_activity_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tamagotchi_mood",
            name="last_interaction_time",
        ),
        migrations.RemoveField(
            model_name="tamagotchi_mood",
            name="rest_start_time",
        ),
        migrations.AddField(
            model_name="tamagotchi_mood",
            name="is_rest_started",
            field=models.BooleanField(default=False),
        ),
    ]
