# Generated by Django 5.0.6 on 2024-05-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tamagotchi", "0012_remove_tamagotchi_mood_last_interaction_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tamagotchi_mood",
            old_name="is_rest_started",
            new_name="is_in_rest",
        ),
    ]
